
modLoader="javafml"
loaderVersion="[35,)"
license="All Rights Reserved"
[[mods]]
modId="bentenmobmod" 
version="${1.4  }" 
displayName="Ben10 Mob Mod" 
logoFile="examplemod.png"
credits="Ben10 mob mod by Yusuf Ismail. PierogiP for drawing some of the items in the mod." 
description='''
Villains and heros in the Ben 10 series. Villains coming out first. In beta stages.

Dont not copy my mod.

made by Yusuf Ismail.

Github is https://github.com/realyusufismail

join discord for support and teasers https://discord.gg/g858J6q

PierogiP: https://www.curseforge.com/members/polisch_pierogi/
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.ben10mobmod]] #optional
   
    modId="forge"
    mandatory=true
    versionRange="[35,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.ben10mobmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
