
modLoader="javafml"
loaderVersion="[36,)"
license="BSD 3-Clause License"
issueTrackerURL="https://github.com/realyusufismail/custom-mod/issues" #optional
[[mods]]
modId="bentenmod"
version="${1.12}"
displayName="Ben10 Mob Mod" 
updateJSONURL="https://raw.githubusercontent.com/realyusufismail/custom-mod/1.15.5-beta/src/main/java/bentenmod-updater.json" #optional
displayURL="https://realyusufismail.github.io/custom-mod/recipes.html" #optional
logoFile="headerimg.png"
credits="Ben10 mob mod by Yusuf Ismail. PierogiP for drawing some of the items in the mod and 
gentworm for helping me with my code." 

authors="Yusuf Ismail and gentworm" #optional
description='''
Villains and heros in the Ben 10 series. Villains coming out first.	

Dont not copy my mod.

made by Yusuf Ismail.

Github is https://github.com/realyusufismail

join discord for support and teasers https://discord.gg/g858J6q

PierogiP: https://www.curseforge.com/members/polisch_pierogi/

gentworm: https://www.curseforge.com/members/gentworm/followers
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.bentenmod]] #optional
   
    modId="forge"
    mandatory=true
    versionRange="[36,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.bentenmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"
   
    [[dependencies.bentenmod]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.16.4-50,)"
    ordering="NONE"
    side="BOTH"
    
    [[dependencies.bentenmod]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.0.30,)"
    ordering="BEFORE"
    side="BOTH"

